---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - '*'
  resources:
  - services/status
  verbs:
  - get
- apiGroups:
  - teamdev.com
  resources:
  - keyvaluedata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - teamdev.com
  resources:
  - keyvaluedata/finalizers
  verbs:
  - update
- apiGroups:
  - teamdev.com
  resources:
  - keyvaluedata/status
  verbs:
  - get
  - patch
  - update
