kind: Namespace
apiVersion: v1
metadata:
  name: storage
  labels:
    name: storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  namespace: storage
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: jackman2001/key-value-storage:v1.0
          ports:
            - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app: storage
spec:
  ports:
    - targetPort: 8181
      port: 8181
  selector:
    app: storage
